services:
  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}_test 
    ports:
      - "5433:5432" 
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}_test"]
      interval: 3s
      timeout: 3s
      retries: 3

  test_backend_api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: asi_movies-api-test
    ports:
      - "8001:8000" 
    env_file:
      - ./.env
    environment:
      - DB_HOST=test_db 
      - DB_NAME=${DB_NAME}_test
    depends_on:
      test_db:
        condition: service_healthy

  locust:
    image: locustio/locust:2.29.1 
    container_name: asi_movies-locust-test
    ports:
      - "8089:8089" 
    volumes:
      - ./tests/load:/mnt/locust
    environment:
      - LOCUST_LOCUSTFILE=/mnt/locust/locustfile.py
    command: --host http://test_backend_api:8000
    depends_on:
      - test_backend_api